#
# ~/.bashrc
#

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="$PATH:$HOME/dev/flutter/bin"

source $HOME/.dotfiles/shell/aliases
source $HOME/.dotfiles/shell/functions


xhost +local:root > /dev/null 2>&1
complete -cf sudo
shopt -s checkwinsize
shopt -s expand_aliases


