source '/usr/share/zsh-antigen/antigen.zsh'

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Interpret return key as command accept line
bindkey '^[OM' accept-line 

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

antigen bundle git
antigen bundle npm
antigen bundle encode64
antigen bundle colorize
antigen bundle github
antigen bundle python
antigen bundle capistrano
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions

# antigen bundle rails
# antigen bundle ruby
# antigen bundle bundler

# Tell Antigen that you're done.
antigen apply

# export PATH="$PATH:$HOME/dev/flutter/bin"
# export PATH="$PATH:$HOME/dev/flutter"
export PATH="$PATH:$HOME/.local/bin"

# Load the theme.
source "$HOME/.dotfiles/shell/wild-berries.zsh-theme"

source $HOME/.dotfiles/shell/aliases
source $HOME/.dotfiles/shell/functions

neofetch
