# Default values for engine and program of search
# The name of the engine/program needs to be exactly as declared on the listing next below
default:
  engine: duckduckgo
  program: system-default

# To add another engine, follow the structure of engine_name and query keys
# Declare where the search term (-t) needs to be in the URL by putting the word TERM
engine:
  google:
    query: https://www.google.com/search?q=TERM
  youtube:
    query: https://www.youtube.com/results?search_query=TERM
  duckduckgo:
    query: https://www.duckduckgo.com/?q=TERM
  netflix:
    query: https://www.netflix.com/search?q=TERM
  stack_overflow:
    query: https://stackoverflow.com/search?q=TERM
  google_maps:
    query: https://www.google.com/maps/search/TERM
  translate:
    query: https://translate.google.com/?sl=auto&tl=$LANG&text=TERM
  reddit:
    query: https://www.reddit.com/search/?q=TERM
  twitter:
    query: https://twitter.com/search?q=TERM
  hackaday:
    query: https://hackaday.com/?s=TERM

program:
  firefox:
    command: firefox
  qutebrowser:
    command: qutebrowser
  chrome:
    command: google-chrome-stable
  curl:
    command: curl
  system-default:
    command: xdg-open
