Settings:
  Power:
    Shutdown: x-terminal-emulator -e 'bash -c "sudo poweroff"'
    Restart: x-terminal-emulator -e 'bash -c "sudo reboot"'
    Lock: xscreensaver-command -lock
  Network: x-terminal-emulator -e nmtui
  Self-Host:
    Pi-hole: firefox-esr http://192.168.18.18/admin/index.php
    Yuno-Host: xdg-open https://gabo.link
  ssh:
    VPS: x-terminal-emulator -e 'zsh -c "ssh admin@gabo.link"'
    pi: x-terminal-emulator -e 'zsh -c "ssh pi@192.168.18.18"'
  Sound: x-terminal-emulator -e alsamixer
  Packages: x-terminal-emulator -e 'bash -c "sudo apt update; zsh"'
  Bluetooth: blueman-manager
  Screenshot:
    Fullscreen: scrot '/home/gabo/Pictures/screenshots/%Y-%m-%d-%H_%M_%S.jpg'
    Selected: scrot -s '/home/gabo/Pictures/screenshots/%Y-%m-%d-%H_%M_%S.jpg'
  Displays: arandr
  Appearance: lxappearance
  Repos: dmenu_tgit
  Windows: $HOME/packages/tinytools/twindow/dmenu_twindow
  Keyboard: fcitx-configtool
  Background: sxiv -t -o $HOME/Pictures/wallpapers | xargs xwallpaper --stretch
  Dotfiles:
    vim: codium $HOME/.vimrc
    bash: codium $HOME/.bashrc
    i3: codium $HOME/.i3/config
    userChrome: codium $HOME/.mozilla/firefox/9lkm9tdr.default/chrome
    tmenus: codium $HOME/tmenus
    install-script: codium $HOME/install-script.sh
  Monitor: 
    Weather: x-terminal-emulator -e 'bash -c "curl wttr.in; zsh"'
    Resources: x-terminal-emulator -e 'zsh -c "bpytop; zsh"'
  tmenu: tmenu $HOME/packages/tinytools/tmenu/menu.yaml
  About: x-terminal-emulator -e 'zsh -c "neofetch; zsh"'